spring:
  application:
    name: issuer
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://psql-issuer:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

